server:
  port: 8082
  servlet:
    context-path: /authentication

spring:
  application:
    name: AUTHENTICATION-SERVICE

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost

jwt:
  secret-key: 1YaijS7kBEWidr8VIZ03bhsvUuc9sH/qh7KsY4rBogH/+zxqLKvV4w5FZDwNlhoXsPdR2kptxtwVwAxX79s4zKvfmj0YZZk/PZmMGHcm/Bo=
