server:
  port: 8082
  servlet:
    context-path: /authentication

spring:
  application:
    name: AUTHENTICATION-SERVICE
  datasource:
  url: jdbc:mysql://localhost:3306/authentication
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: 123456

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost

jwt:
  secret-key: 1YaijS7kBEWidr8VIZ03bhsvUuc9sH/qh7KsY4rBogH/+zxqLKvV4w5FZDwNlhoXsPdR2kptxtwVwAxX79s4zKvfmj0YZZk/PZmMGHcm/Bo=
