spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/identity
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379
jwt:
  secret-key: ${JWT_SECRET_KEY:LlXbOuam4UBLZOg9uylp4Bp4IzL0p9Vb/leiOexBiXBZnHGkzH/lVxamrIjm/pv6rDDsqLmFhlfTC2rGzLf603+SkhUFr4OTh/rAcCPfx1Y=}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring-cloud-bus:
  message: "Hello Spring Cloud Bus"
