spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST:mysql}:${DATABASE_PORT:3306}/profiles
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:123456}

  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
